- hosts: localhost
  roles:
    - brew
    - appstore
    - android
    - defaults
    - elasticsearch
    - nodejs
    - ruby
    - shell

  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}"
    GHQ_ROOT: "{{ lookup('env', 'HOME') }}/src"
    PATH: "{{ lookup('env', 'HOME') }}/bin:{{ lookup('env', 'PATH') }}"
