- hosts: localhost
  roles:
    - brew
    - appstore
    - nodejs
    - ruby
    - shell
    - android
  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}"
    GHQ_ROOT: "{{ lookup('env', 'HOME') }}/src"
    PATH: "{{ lookup('env', 'HOME') }}/bin:{{ lookup('env', 'PATH') }}"
