- hosts: localhost
  roles:
    - brew
    - appstore
    - defaults
    - node
    - ruby
    - shell
    - karabiner-elements
    - vscode

  environment:
    GOPATH: "{{ lookup('env', 'HOME') }}"
    GHQ_ROOT: "{{ lookup('env', 'HOME') }}/src"
    PATH: "{{ lookup('env', 'HOME') }}/bin:{{ lookup('env', 'PATH') }}"
