- file:
    path: ~/.config
    state: directory

- file:
    path: ~/.config/karabiner
    state: directory

- file:
    src: ~/src/github.com/gyugyu/osx-provisioning/roles/karabiner-elements/files/karabiner.json
    dest: ~/.config/karabiner/karabiner.json
    state: link

- command: open /Applications/Karabiner-Elements.app