- file: path=~/.nodenv state=directory

- file: src=~/src/github.com/gyugyu/osx-provisioning/roles/node/files/default-packages dest=~/.nodenv/default-packages state=link

- include: install.yml
  with_items:
    - 4.3.2
    - 7.3.0

- command: nodenv global 7.3.0
