- file: path=~/.rbenv state=directory

- file: src=~/src/github.com/gyugyu/osx-provisioning/roles/ruby/files/default-gems dest=~/.rbenv/default-gems state=link

- file: src=~/src/github.com/gyugyu/osx-provisioning/roles/ruby/files/gemrc dest=~/.gemrc state=link

- stat: path=~/.rbenv/versions/2.3.3
  register: st

- command: rbenv install 2.3.3
  when: not st.stat.exists

- command: rbenv global 2.3.3
